# Generated by Django 4.2.2 on 2023-06-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('ID_Card', models.ImageField(upload_to='')),
                ('Letter', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('Employed', models.BooleanField(default=True)),
                ('Title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('Salary', models.IntegerField(null=True)),
                ('Referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanresource.reference')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanresource.employee')),
            ],
        ),
    ]
