# Generated by Django 4.2.2 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SetBy", models.CharField(max_length=200)),
                ("TaskTitle", models.CharField(max_length=300)),
                ("TaskDetail", models.CharField(max_length=5000)),
                ("SetTo", models.CharField(max_length=200)),
            ],
        ),
    ]
