# Generated by Django 4.2.2 on 2023-08-02 18:30

from django.db import migrations, models
import humanresource.models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="employee_image",
            field=models.ImageField(
                default="posts/default.jpg",
                upload_to=humanresource.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
