# Generated by Django 4.2.2 on 2023-06-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_employee_password_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Referer',
        ),
    ]
