# Generated by Django 4.2.2 on 2023-09-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humanresource.employee'),
        ),
    ]
