# Generated by Django 4.2.2 on 2023-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0004_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RoleName", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(model_name="employee", name="title",),
        migrations.AddField(
            model_name="employee",
            name="Role",
            field=models.ManyToManyField(to="humanresource.role"),
        ),
    ]
