# Generated by Django 4.2.2 on 2023-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0005_role_remove_employee_title_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(default='', max_length=255)),
                ('Job_Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
