# Generated by Django 4.2.2 on 2023-09-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0006_job_delete_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Job_description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="jobSetBy",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Task_name", models.CharField(default="", max_length=255)),
                ("Task_description", models.CharField(default="", max_length=1000)),
                (
                    "Task_set_By",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_set_by",
                        to="humanresource.employee",
                    ),
                ),
                (
                    "Task_set_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_set_to",
                        to="humanresource.employee",
                    ),
                ),
            ],
        ),
    ]
