# Generated by Django 4.2.2 on 2023-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0007_job_job_description_job_jobsetby_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Task_completed",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job", name="JobName", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="Job_description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job", name="jobSetBy", field=models.CharField(max_length=255),
        ),
    ]
