# Generated by Django 4.2.2 on 2023-09-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0008_task_task_completed_alter_job_jobname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmailTitle", models.CharField(max_length=500)),
                ("EmailSubject", models.CharField(max_length=500)),
                (
                    "SentBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Email_sent_by",
                        to="humanresource.employee",
                    ),
                ),
                (
                    "SentTo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Email_sent_To",
                        to="humanresource.employee",
                    ),
                ),
            ],
        ),
    ]
