# Generated by Django 4.2.2 on 2023-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0009_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="EmailBody",
            field=models.CharField(default="email body", max_length=5000),
            preserve_default=False,
        ),
    ]
