# Generated by Django 4.2.2 on 2023-09-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0010_email_emailbody"),
    ]

    operations = [
        migrations.RemoveField(model_name="email", name="EmailTitle",),
    ]
