# Generated by Django 4.2.2 on 2023-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanresource", "0011_remove_email_emailtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="email", name="seen", field=models.BooleanField(default=False),
        ),
    ]
